name: Links

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lycheeverse/lychee-action@v2
        with:
          args: >-
            --no-progress --verbose
            --accept 429
            --exclude openai.com
            --exclude openreview.net
            README.md CONTRIBUTING.md
